version: "3.9"
services:
  app:
    container_name: hyunmantle
    image: choih0401/hyunmantle
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8899:80"
    volumes:
      - .:/app